from __future__ import annotations

CORE_INDEXES: dict[str, str] = {
    "000001.SH": "上证指数",
    "399001.SZ": "深证成指",
    "399006.SZ": "创业板指",
    "000300.SH": "沪深300",
    "000905.SH": "中证500",
    "000852.SH": "中证1000",
}

WAREHOUSE_SCHEMAS: dict[str, list[str]] = {
    "instruments": [
        "code",
        "symbol",
        "exchange",
        "name",
        "market",
        "industry",
        "list_date",
        "delist_date",
        "status",
        "source_provider",
        "source_updated_at",
    ],
    "trading_calendar": [
        "trade_date",
        "exchange",
        "is_open",
        "source_provider",
        "source_updated_at",
    ],
    "daily_bars": [
        "code",
        "symbol",
        "exchange",
        "trade_date",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "amount",
        "price_adjustment",
        "source_provider",
        "source_updated_at",
    ],
    "index_daily_bars": [
        "index_code",
        "symbol",
        "name",
        "trade_date",
        "open",
        "high",
        "low",
        "close",
        "volume",
        "amount",
        "source_provider",
        "source_updated_at",
    ],
    "adj_factors": [
        "code",
        "symbol",
        "trade_date",
        "adj_factor",
        "source_provider",
        "source_updated_at",
    ],
}
